import {StyleSheet} from 'react-native';
import {getResponsiveValue} from '../../Services/utils';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f7a42d',
    paddingBottom: getResponsiveValue(50),
  },
  header: {
    marginTop: getResponsiveValue(20),
  },
  body: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: getResponsiveValue(20),
  },
  itens: {
    width: '90%',
    backgroundColor: '#43a7f5',
    padding: getResponsiveValue(10),
    borderRadius: getResponsiveValue(8),
    marginVertical: getResponsiveValue(10),
    marginHorizontal: '5%',
    alignItems: 'center',
  },
  exclude: {
    backgroundColor: 'red',
    width: getResponsiveValue(20),
    height: getResponsiveValue(20),
    borderRadius: getResponsiveValue(10),
    alignItems: 'center',
    justifyContent: 'center',
    padding: getResponsiveValue(0),
    top: getResponsiveValue(-20),
    right: '-52%',
  },
  excludeText: {
    color: '#FFF',
    fontSize: getResponsiveValue(16),
    fontWeight: '500',
    textAlign: 'center',
    lineHeight: getResponsiveValue(16),
  },
  line1: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  check: {
    width: getResponsiveValue(20),
    height: getResponsiveValue(20),
    borderRadius: getResponsiveValue(20),
    backgroundColor: '#FFF',
    borderWidth: getResponsiveValue(2),
    borderColor: '#638DAF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  line2: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: getResponsiveValue(4),
  },
  line3: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: getResponsiveValue(4),
  },
  itensQtd: {
    height: getResponsiveValue(30),
    paddingHorizontal: getResponsiveValue(5),
    paddingVertical: getResponsiveValue(4),
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#638DAF',
    borderRadius: getResponsiveValue(14),
  },
  title: {
    fontSize: getResponsiveValue(16),
    fontWeight: '700',
    textAlign: 'center',
    color: 'black',
  },
  AddNewTouch: {
    backgroundColor: '#43a7f5',
    alignContent: 'center',
    justifyContent: 'center',
    borderRadius: getResponsiveValue(30),
    width: getResponsiveValue(60),
    height: getResponsiveValue(60),
  },
  AddNew: {
    fontSize: getResponsiveValue(40),
    fontWeight: '700',
    textAlign: 'center',
    color: 'black',
  },
  subtract: {
    backgroundColor: '#FFF',
    width: getResponsiveValue(20),
    height: getResponsiveValue(20),
    borderRadius: getResponsiveValue(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  subtractText: {
    width: getResponsiveValue(8),
    height: getResponsiveValue(2),
    backgroundColor: '#4D7595',
  },
  Number: {
    fontFamily: 'Rambla-Bold',
    fontSize: getResponsiveValue(13),
    lineHeight: getResponsiveValue(14.69),
    color: '#FFF',
    marginHorizontal: getResponsiveValue(7),
  },
  ADD: {
    backgroundColor: '#203F58',
    width: getResponsiveValue(20),
    height: getResponsiveValue(20),
    borderRadius: getResponsiveValue(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  ADDTextHorizontal: {
    width: getResponsiveValue(8),
    height: getResponsiveValue(2),
    backgroundColor: '#FFF',
    top: getResponsiveValue(5),
  },
  ADDTextVertical: {
    width: getResponsiveValue(2),
    height: getResponsiveValue(8),
    backgroundColor: '#FFF',
  },
  descriptionValue: {
    width: '100%',
    borderRadius: getResponsiveValue(8),
    backgroundColor: '#638DAF',
    padding: getResponsiveValue(5),
    fontSize: getResponsiveValue(16),
    fontWeight: '700',
    textAlign: 'center',
    color: 'black',
  },
  priceComp: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '30%',
    borderRadius: getResponsiveValue(8),
    backgroundColor: '#638DAF',
    padding: getResponsiveValue(5),
    fontSize: getResponsiveValue(14),
    fontWeight: '700',
    color: 'black',
  },
  priceValue: {
    borderRadius: getResponsiveValue(8),
    width: '70%',
    textAlign: 'left',
    backgroundColor: '#638DAF',
    padding: getResponsiveValue(0),
    margin: getResponsiveValue(0),
    marginStart: getResponsiveValue(4),
    fontSize: getResponsiveValue(14),
    fontWeight: '700',
    color: 'black',
  },
  priceValueRS: {
    borderRadius: getResponsiveValue(8),
    backgroundColor: '#638DAF',
    padding: getResponsiveValue(0),
    margin: getResponsiveValue(0),
    fontSize: getResponsiveValue(14),
    fontWeight: '700',
    color: 'black',
  },
  valorUn: {
    fontSize: getResponsiveValue(16),
    color: 'black',
    fontWeight: '700',
    marginRight: getResponsiveValue(10),
  },
});

export default styles;
